AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-python3.9

  Sample SAM Template for lambda-python3.9

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 256

Parameters:
  EndpointUrl:
    Type: String
    Description: EndpointUrl
    Default: none

# Example of Mappings
# Mappings:
#   EnvVariables:
#     stage:
#         var1: user1
#         API_BASE_URL: https://baseurl1.com
#     prod:
#         var1: user2
#         API_BASE_URL: https://baseurl2.com

# SAM Connectors: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/reference-sam-connector.html
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-connector.html
# More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
# More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api

Resources:

  # Declare the lambda role manually
  OrchestrationLambdaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      # This AWS managed policy allows the lambda function to write logs to cloudwatch
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      # Add permission to retrieve SSM parameters from the store
      Policies:
        - PolicyName: SsmGet
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Sid: GetParameterFromStore
                Action:
                  - ssm:GetParameter
                Resource: !Sub
                  - "arn:aws:ssm:eu-west-2:${AccountId}:parameter/*"
                  - AccountId: !Ref AWS::AccountId

        # Add permission to decrypt those SSM Parameters with the auto-generated KMS key
        - PolicyName: KmsDecrypt
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Sid: DecryptWithKMS
                Action:
                  - kms:Decrypt
                Resource: !Sub
                  - "arn:aws:kms:eu-west-2:${AccountId}:key/*"
                  - AccountId: !Ref AWS::AccountId

  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/orchestration/
      Handler: app.orchestration_handler.orchestration_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Layers:
        - !Ref SharedLayer
      Environment:
        Variables:
          EndpointUrl: !Ref EndpointUrl
      Events:
        Calculate:
          Type: Api
          Properties:
            Path: /calculate
            Method: get
      Role: !GetAtt OrchestrationLambdaIAMRole.Arn

  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: lambdas/shared/
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9 # Required to have AWS SAM build this layer

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DirectCareApi:
    Description: "API Gateway endpoint URL for Prod stage for the Main function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/calculate/"
  DirectCareFunction:
    Description: "Main Lambda Function ARN"
    Value: !GetAtt MainFunction.Arn
  DirectCareFunctionIamRole:
    Description: "Implicit IAM Role created for the Main function"
    Value: !GetAtt OrchestrationLambdaIAMRole.Arn
