# Generates a terraform plan file and uploads it to s3 as an artifact
version: 0.2
phases:
  install:
    commands:
      - make prepare-terraform
      - python -m pip install poetry

  build:
    commands:
      - echo ENV is $ENV
      - make package-lambdas env=$ENV
      - make DANGER-tf-init env=$ENV
      - make tf-plan-with-output version=${CODEBUILD_RESOLVED_SOURCE_VERSION}

artifacts:
  files:
    - terraform/tf_plan_commit_${CODEBUILD_RESOLVED_SOURCE_VERSION}
    - build/lambda_archives/*
  name: terraform-plan-$ENV-`date +"%Y-%m-%d_%T"`
