version: 0.2
phases:
  install:
    commands:
      - git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.9.0
      - echo '. $HOME/.asdf/asdf.sh' >> ~/.bashrc
      - source $HOME/.asdf/asdf.sh
      - asdf plugin add python
      - asdf plugin-add poetry https://github.com/asdf-community/asdf-poetry.git
      - asdf install
  build:
    commands:
      # trigger the integration tests here
      - echo 'Running integration tests'
      - STACK_NAME=`echo ${ENV_STACK_NAME} | tr -cd '[a-zA-Z0-9-]'`
      - echo STACK_NAME ${STACK_NAME}
      - echo ENV_PIPELINE_EXECUTION_ROLE ${ENV_PIPELINE_EXECUTION_ROLE}
      - . ./scripts/assume_role.sh ${ENV_PIPELINE_EXECUTION_ROLE} integration-test
      - stack_resources=`aws cloudformation describe-stack-resources --stack-name ${STACK_NAME}`
      - serverlessRestApi=`echo $stack_resources | jq -r '.StackResources[] |select(.ResourceType=="AWS::ApiGateway::RestApi").PhysicalResourceId'`
      - BASE_URL=https://${serverlessRestApi}.execute-api.eu-west-2.amazonaws.com/record/
      - echo BASE_URL ${BASE_URL}
      - make install
      - make integration-test
    reports:
      cucumber-reports:
        files:
          - "reports/cucumber_json.json"
        file-format: "CUCUMBERJSON"
