version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli aws-sam-cli
      # Enable docker https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      - sam build --use-container --template ${SAM_TEMPLATE}
      - . ./scripts/assume_role.sh ${TESTING_PIPELINE_EXECUTION_ROLE} test-package
      - sam package --s3-bucket ${TESTING_ARTIFACT_BUCKET}
        --region ${TESTING_REGION}
        --output-template-file packaged-test.yaml
      - . ./scripts/assume_role.sh ${INT_PIPELINE_EXECUTION_ROLE} int-package
      - sam package --s3-bucket ${INT_ARTIFACT_BUCKET}
        --region ${INT_REGION}
        --output-template-file packaged-int.yaml
artifacts:
  files:
    - packaged-test.yaml
    - packaged-int.yaml
    - scripts/assume_role.sh
    - pipeline/*
