name: Build

on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # This causes all history to be fetched, which is required for calculate-version to function

      - name: Install Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Update apt repositories
        run: sudo apt update

      - name: Upgrade python packaging tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install poetry
        run: pip install poetry

      - name: Cache poetry packages
        uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-build-cache-poetry-packages-${{ hashFiles('**/poetry.lock') }}

      - name: Install python packages
        run: poetry install

      - name: Set SPEC_VERSION env var
        run: echo "USE THIS TO SET VERSION NUMBER <TODO>"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::038755702666:role/github-managed-pipeline-r-CloudFormationDeployRole-1K2TWJ9088EOI
          role-session-name: github-actions

      - shell: bash
        name: deploy_pipeline
        env:
          CODEBUILD_TOKEN: ${{ secrets.CODEBUILD_TOKEN }}
          CODEBUILD_USER: ${{ secrets.CODEBUILD_USER }}
        run: |
          cat <<EOF > .env.build
          CODEBUILD_TOKEN="$CODEBUILD_TOKEN"
          CODEBUILD_USER="$CODEBUILD_USER"
          EOF
          source .env.build
          ./cloudformation/scripts/deploy_pipeline.sh 4 sam_deployment
          rm .env.build
