name: Create PR AWS infra

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: create-pr-aws-infra
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::436014718090:role/github-role
          role-session-name: github-actions

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Switch to PR and package lambdas
        run: |
          export PULL_REQUEST_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo Pull request number is ${PULL_REQUEST_NUMBER}
          make switch-to-pr-${PULL_REQUEST_NUMBER}

      - name: Terraform apply
        run: make tf-apply

      - name: Output Terraform
        run: cd terraform && export URL=$(terraform output api_gateway_url) && echo $URL && echo ::notice title=API Gateway endpoint::$URL
