name: Create PR AWS infra

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: create-pr-aws-infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Update repo
        run: sudo apt update

      - name: Install Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Switch to PR
      - run: |
          export PULL_REQUEST_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo ${PULL_REQUEST_NUMBER}
          make switch-to-pr-${PULL_REQUEST_NUMBER}

      - name: Terraform plan
        run: make terraform-plan

      - name: Terraform apply
        run: make terraform-apply
