name: Destroy PR AWS infra

on:
  pull_request:
    types: [ closed ]

jobs:
  build:
    name: destroy-pr-aws-infra
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::436014718090:role/github-role
          role-session-name: github-actions

      - name: Update repo
        run: sudo apt update

      - name: Install Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Destroy PR resources
        run: |
          export PULL_REQUEST_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo Pull request number is ${PULL_REQUEST_NUMBER}
          make tf-destroy-pr-${PULL_REQUEST_NUMBER}
